version: '3.3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Ayouda123
      MYSQL_DATABASE: kaddem
      MYSQL_USER: hadil
      MYSQL_PASSWORD: Ayouda123
    ports:
      - "3307:3306"  # Expose MySQL on host port 3307

  gestion-station-ski-backend:
    image: hadildridi/kaddem:latest  # Use the existing image
    ports:
      - "8089:8089"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/kaddem?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: hadil
      SPRING_DATASOURCE_PASSWORD: Ayouda123
      SPRING_SERVER_PORT: 8089
